images:
  cloudflared:
    repository: "cloudflare/cloudflared"
    tag: "latest"
    pullPolicy: "Always"
  alexprinter:
    repository: "bmo75/alex-printer-build-counter"
    tag: "latest"
    pullPolicy: "Always"

tunnel:
  existingSecret: cf-token
  tokenKey: TUNNEL_TOKEN
  hostname: "alexprinter.bmosan.com"
  