---
# values.yaml (move this to a separate file)
cloudflared:
  image: cloudflare/cloudflared:latest
  command: "tunnel --no-autoupdate run"
  env:
    - name: TUNNEL_TOKEN
      valueFrom:
        secretKeyRef:
          name: cf-token
          key: TUNNEL_TOKEN
  replicas: 1

alexprinter:
  image: bmo75/alex-printer-build-counter:latest
  replicas: 1

network:
  name: helm-alexprinter-tunnel
